question_data = [
 {"category": "Science: Computers",
  "type": "boolean", "difficulty": "medium",
  "question": "The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.",
  "correct_answer": "False",
  "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
  "question": "The first computer bug was formed by faulty wires.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
  "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
  "incorrect_answers": ["False"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
  "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
  "question": "Ada Lovelace is often considered the first computer programmer.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
  "question": "The first dual-core CPU was the Intel Pentium D.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
  "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
  "question": "Linux was first created as an alternative to Windows XP.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
  "question": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
  "correct_answer": "False", "incorrect_answers": ["True"]}
]
